### ISSUE TITLE
Ampripper out of stock

### ISSUE THREAD

**Issue by RazJuan** [g1sbi/qaz-cyberdeck#1]
Hello,

I loved your guide quite a lot, and I would be interested in making a cyberdeck following your design but it seems that the ampripper 3000 is out of stock.

Would I be able to use any 5V 3A power supply such as [this one](https://www.makerfocus.com/products/raspberry-pi-expansion-board-ups-pack-standard-power-supply)?

Many thanks,
Raz

**Comment by g1sbi** [comment]
@RazJuan as far as the power requirements go it looks okay, however, The form factor would not fit the case at all. Unless you'd know how to modify the case to fit your needs, it doesn't seem possible.

The good news is that the [Ampripper 4000](https://www.kickstarter.com/projects/ksd/ampripper-4000-next-gen-battery-charger-and-boost-module) is coming out and shipping soon.

**Comment by RazJuan** [comment]
@g1sbi thank you for the quick response, I'll make sure to get that. I'll get this closed.
